version: "3"
services:
  db:
    image: mysql:latest
    container_name: todotweet_db
    restart: always
    # 環境変数（.envから参照させる）
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    # ホストport:コンテナport
    ports:
      - ${DB_PORT}:3306
